### ISSUE TITLE
Bug with omero metadata

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#201]
@giovp in this code

```python
# if image, read channels metadata
if raster_type == "image" and channels_metadata is not None:
    channels: list[Any] = fmt.channels_from_metadata(channels_metadata)
axes = [i["name"] for i in node.metadata["axes"]]
if len(datasets) > 1:
    multiscale_image = {}
    for i, d in enumerate(datasets):
        data = node.load(Multiscales).array(resolution=d, version=fmt.version)
        multiscale_image[f"scale{i}"] = DataArray(
            data,
            name=name,
            dims=axes,
            coords={"c": channels} if raster_type == "image" else {},
        )
    msi = MultiscaleSpatialImage.from_dict(multiscale_image)
    _set_transformations(msi, transformations)
    return compute_coordinates(msi)
data = node.load(Multiscales).array(resolution=datasets[0], version=fmt.version)
si = SpatialImage(
    data,
    name=name,
    dims=axes,
    coords={"c": channels} if raster_type == "image" else {},
)
```

The first `if` sometimes is not executed. In those cases the variable `channels` is not defined and I get this error:

```
/Users/macbook/miniconda3/envs/ome/bin/python /Users/macbook/embl/projects/basel/spatialdata-sandbox/examples/xenium_and_visium.py 
/Users/macbook/miniconda3/envs/ome/lib/python3.10/site-packages/geopandas/_compat.py:123: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/Users/macbook/embl/projects/basel/spatialdata/src/spatialdata/__init__.py:9: UserWarning: Geopandas was set to use PyGEOS, changing to shapely 2.0 with:

	geopandas.options.use_pygeos = True

If you intended to use PyGEOS, set the option to False.
  _check_geopandas_using_shapely()
Traceback (most recent call last):
  File "/Users/macbook/embl/projects/basel/spatialdata-sandbox/examples/xenium_and_visium.py", line 21, in <module>
    xenium_sdata = sd.read_zarr(XENIUM_SDATA_PATH)
  File "/Users/macbook/embl/projects/basel/spatialdata/src/spatialdata/_io/io_zarr.py", line 36, in read_zarr
    images[k] = _read_multiscale(f_elem_store, raster_type="image")
  File "/Users/macbook/embl/projects/basel/spatialdata/src/spatialdata/_io/io_raster.py", line 83, in _read_multiscale
    coords={"c": channels} if raster_type == "image" else {},
UnboundLocalError: local variable 'channels' referenced before assignment

Process finished with exit code 1
```

Since you are more familiar with this part of the code, could you please add a fix and tests?

**Comment by LucaMarconato** [comment]
Actually it was a very quick fix, please have a look at this PR I made: https://github.com/scverse/spatialdata/pull/202.

I think there is no need to add tests for this.
