### ISSUE TITLE
Installation error in Intel processor Macbook

### ISSUE THREAD

**Issue by shashkat** [scverse/spatialdata#632]
Hello there, thanks for making this amazing package! I want to use spatialdata as I am hoping to interactively visualize VisiumHD data using napari. I tried installing the package using `pip install "spatialdata[extra]"`, but I am getting an installation error. 
I created a new conda env using: 
```
conda create --name spatialdata python=3.9.0
conda activate spatialdata
```

Installation output with error:
```
% pip install "spatialdata[extra]"
Collecting spatialdata[extra]
  Downloading spatialdata-0.2.1-py3-none-any.whl.metadata (9.4 kB)
Collecting anndata>=0.9.1 (from spatialdata[extra])
  Using cached anndata-0.10.8-py3-none-any.whl.metadata (6.6 kB)
Collecting click (from spatialdata[extra])
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting dask-image (from spatialdata[extra])
  Using cached dask_image-2024.5.3-py3-none-any.whl.metadata (2.8 kB)
Collecting dask>=2024.4.1 (from spatialdata[extra])
  Using cached dask-2024.7.0-py3-none-any.whl.metadata (3.8 kB)
Collecting fsspec<=2023.6 (from spatialdata[extra])
  Using cached fsspec-2023.6.0-py3-none-any.whl.metadata (6.7 kB)
Collecting geopandas>=0.14 (from spatialdata[extra])
  Using cached geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)
Collecting multiscale-spatial-image>=1.0.0 (from spatialdata[extra])
  Using cached multiscale_spatial_image-1.0.0-py3-none-any.whl.metadata (21 kB)
Collecting networkx (from spatialdata[extra])
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting numpy (from spatialdata[extra])
  Using cached numpy-2.0.0-cp39-cp39-macosx_10_9_x86_64.whl.metadata (60 kB)
Collecting ome-zarr>=0.8.4 (from spatialdata[extra])
  Using cached ome_zarr-0.9.0-py3-none-any.whl.metadata (3.4 kB)
Collecting pandas (from spatialdata[extra])
  Using cached pandas-2.2.2-cp39-cp39-macosx_10_9_x86_64.whl.metadata (19 kB)
Collecting pooch (from spatialdata[extra])
  Using cached pooch-1.8.2-py3-none-any.whl.metadata (10 kB)
Collecting pyarrow (from spatialdata[extra])
  Using cached pyarrow-16.1.0-cp39-cp39-macosx_10_15_x86_64.whl.metadata (3.0 kB)
Collecting rich (from spatialdata[extra])
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
Collecting scikit-image (from spatialdata[extra])
  Using cached scikit_image-0.24.0-cp39-cp39-macosx_10_9_x86_64.whl.metadata (14 kB)
Collecting scipy (from spatialdata[extra])
  Using cached scipy-1.13.1-cp39-cp39-macosx_10_9_x86_64.whl.metadata (60 kB)
Requirement already satisfied: setuptools in /opt/anaconda3/envs/spatialdata/lib/python3.9/site-packages (from spatialdata[extra]) (69.5.1)
Collecting shapely>=2.0.1 (from spatialdata[extra])
  Using cached shapely-2.0.4-cp39-cp39-macosx_10_9_x86_64.whl.metadata (7.0 kB)
Collecting spatial-image>=1.0.0 (from spatialdata[extra])
  Using cached spatial_image-1.1.0-py3-none-any.whl.metadata (5.5 kB)
Collecting typing-extensions>=4.8.0 (from spatialdata[extra])
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting xarray (from spatialdata[extra])
  Using cached xarray-2024.6.0-py3-none-any.whl.metadata (11 kB)
Collecting xarray-datatree (from spatialdata[extra])
  Using cached xarray_datatree-0.0.14-py3-none-any.whl.metadata (6.9 kB)
Collecting xarray-schema (from spatialdata[extra])
  Using cached xarray_schema-0.0.3-py3-none-any.whl.metadata (4.3 kB)
Collecting xarray-spatial>=0.3.5 (from spatialdata[extra])
  Using cached xarray_spatial-0.4.0-py3-none-any.whl.metadata (16 kB)
Collecting zarr (from spatialdata[extra])
  Using cached zarr-2.18.2-py3-none-any.whl.metadata (5.7 kB)
Collecting napari-spatialdata>=0.2.4 (from spatialdata[extra])
  Downloading napari_spatialdata-0.5.0.post1-py3-none-any.whl.metadata (8.1 kB)
Collecting spatialdata-io (from spatialdata[extra])
  Downloading spatialdata_io-0.1.3.post0-py3-none-any.whl.metadata (6.0 kB)
Collecting spatialdata-plot (from spatialdata[extra])
  Downloading spatialdata_plot-0.2.3.post0-py3-none-any.whl.metadata (6.9 kB)
Collecting array-api-compat!=1.5,>1.4 (from anndata>=0.9.1->spatialdata[extra])
  Using cached array_api_compat-1.7.1-py3-none-any.whl.metadata (1.5 kB)
Collecting exceptiongroup (from anndata>=0.9.1->spatialdata[extra])
  Using cached exceptiongroup-1.2.1-py3-none-any.whl.metadata (6.6 kB)
Collecting h5py>=3.1 (from anndata>=0.9.1->spatialdata[extra])
  Using cached h5py-3.11.0-cp39-cp39-macosx_10_9_x86_64.whl.metadata (2.5 kB)
Collecting natsort (from anndata>=0.9.1->spatialdata[extra])
  Using cached natsort-8.4.0-py3-none-any.whl.metadata (21 kB)
Collecting packaging>=20.0 (from anndata>=0.9.1->spatialdata[extra])
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting cloudpickle>=1.5.0 (from dask>=2024.4.1->spatialdata[extra])
  Using cached cloudpickle-3.0.0-py3-none-any.whl.metadata (7.0 kB)
Collecting partd>=1.4.0 (from dask>=2024.4.1->spatialdata[extra])
  Using cached partd-1.4.2-py3-none-any.whl.metadata (4.6 kB)
Collecting pyyaml>=5.3.1 (from dask>=2024.4.1->spatialdata[extra])
  Using cached PyYAML-6.0.1-cp39-cp39-macosx_10_9_x86_64.whl.metadata (2.1 kB)
Collecting toolz>=0.10.0 (from dask>=2024.4.1->spatialdata[extra])
  Using cached toolz-0.12.1-py3-none-any.whl.metadata (5.1 kB)
Collecting importlib-metadata>=4.13.0 (from dask>=2024.4.1->spatialdata[extra])
  Using cached importlib_metadata-8.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting pyogrio>=0.7.2 (from geopandas>=0.14->spatialdata[extra])
  Using cached pyogrio-0.9.0.tar.gz (352 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/opt/anaconda3/envs/spatialdata/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/anaconda3/envs/spatialdata/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/anaconda3/envs/spatialdata/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/pn/qmh53k3s2_gbklgc1hhgh2h80000gr/T/pip-build-env-w_frircu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/pn/qmh53k3s2_gbklgc1hhgh2h80000gr/T/pip-build-env-w_frircu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/pn/qmh53k3s2_gbklgc1hhgh2h80000gr/T/pip-build-env-w_frircu/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
        File "<string>", line 129, in get_gdal_config
        File "<string>", line 85, in get_gdal_config
        File "<string>", line 85, in <dictcomp>
        File "<string>", line 39, in read_response
        File "/opt/anaconda3/envs/spatialdata/lib/python3.9/subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/opt/anaconda3/envs/spatialdata/lib/python3.9/subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/opt/anaconda3/envs/spatialdata/lib/python3.9/subprocess.py", line 947, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/opt/anaconda3/envs/spatialdata/lib/python3.9/subprocess.py", line 1819, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

ouput I get for conda info:
```
% conda info

     active environment : base
    active env location : /opt/anaconda3
            shell level : 1
       user config file : /Users/shashankkatiyar/.condarc
 populated config files :
          conda version : 24.5.0
    conda-build version : 24.5.1
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.5.0=0
                          __osx=10.16=0
                          __unix=0=0
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/shashankkatiyar/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/shashankkatiyar/.conda/envs
               platform : osx-64
             user-agent : conda/24.5.0 requests/2.32.2 CPython/3.12.4 Darwin/23.5.0 OSX/10.16 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 504:20
             netrc file : None
           offline mode : False
```

Details about my Macbook:
```
Processor: 2.4 GHz 8-Core Intel Core i9
MacOS: Sonoma 14.5
```

Any help would be greatly appreciated!
Thanks!

**Comment by LucaMarconato** [comment]
Hi, thank you for providing detailed information. I currently don't have access to an Intel Macbook so I won't be able to reproduce myself (I could get access in 3 weeks if the problem persists). Nevertheless I would recommend the following:

1. I would try to install `spatialdata` using `conda` with `mamba install spatialdata`. Currently `spatialdata-io`, `spatialdata-plot` and `napari-spatialdata` needs to be installed via `pip`, but `pyogrio` would be handed by `conda`, so this may fix your problem.
2. if the above doesn't work, I would try to see if you can reproduce the bug by installing `geopandas>=0.14` from `pip`. In such a case, I would ask you to report the bug in the `geopandas` GitHub Issue tracker (cross referencing this issue).

Please keep us informed about developments 😊

**Comment by shashkat** [comment]
Hello @LucaMarconato, thanks a lot for the quick reply!

I have been able to solve the issue. Here is what I did:
- I created an empty conda environment without any python installation as I think is suggested in the "GDAL master conda builds" section in this page: https://gdal.org/download.html#mac-os
- Then, I installed gdal using: `conda install -c conda-forge gdal`
- Then I installed spatialdata and assisting packages using: `pip install "spatialdata[extra]"` and it worked!

However, I actually wanted to ask a VisiumHD related question, unrelated to installation issues. If you would happen to have any inputs, it would be a great help.

I want to obtain a .cloupe file (it's produced as one of the outputs of the spaceranger count command) at 2um resolution of spots. The file that spaceranger count produces by default has 8um spots. There is a flag of the spaceranger count, called `--custom-bin-size` but it takes values from 10 to 100. I have looked through a lot of 10x documentation but can't seem to find a way to do that. I think this would be a common issue among the community too (this I say because it is a direct next step of nuclei-segmentation task(https://www.10xgenomics.com/analysis-guides/segmentation-visium-hd), which is what I am doing). 
Hence, if anyone has any ideas or has been able to figure it out, could you please give some insights?

Thanks a lot!

**Comment by LucaMarconato** [comment]
Great to hear that you managed to solve the installation issue. I will close the current issue and move the conversation to a new issue in `spatialdata-io`.
